services:
    _defaults:
        autowire: true
        autoconfigure: true

    Forumify\Calendar\:
        resource: '../src/'
        exclude:
            - '../src/**/DataFixture/'
            - '../src/**/DependencyInjection/'
            - '../src/**/Entity/'
